export type GlobalMarketCapEventTone = 'caution' | 'growth' | 'milestone' | 'shift';

export type GlobalMarketCapEvent = {
  year: number;
  companyName: string;
  code: string;
  headline: string;
  detail: string;
  tone: GlobalMarketCapEventTone;
  source: string;
};

export const globalMarketCapEvents = [
  {
    year: 2000,
    companyName: 'Pfizer',
    code: 'PFE',
    headline: 'Pfizer wins Warner-Lambert',
    detail: 'A $116B deal gives Pfizer full control of Lipitor and reshapes big pharma.',
    tone: 'growth',
    source: 'https://www.investopedia.com/companies-owned-by-pfizer-5211303',
  },
  {
    year: 2001,
    companyName: 'Microsoft',
    code: 'MSFT',
    headline: 'Windows XP launches',
    detail: 'Microsoft unifies consumer Windows with the Windows NT line.',
    tone: 'milestone',
    source: 'https://www.wired.com/2001/10/gates-hello-xp-goodbye-dos/',
  },
  {
    year: 2002,
    companyName: 'Microsoft',
    code: 'MSFT',
    headline: 'Antitrust settlement approved',
    detail: 'A federal judge accepts most of the DOJ settlement, setting years of conduct limits.',
    tone: 'caution',
    source: 'https://www.wired.com/2002/11/judge-oks-ms-antitrust-deal',
  },
  {
    year: 2003,
    companyName: 'Pfizer',
    code: 'PFE',
    headline: 'Pfizer buys Pharmacia',
    detail: 'Pfizer expands its portfolio with Celebrex and Pharmacia assets.',
    tone: 'growth',
    source: 'https://money.cnn.com/2003/04/16/news/companies/pfizer_pharmacia/',
  },
  {
    year: 2004,
    companyName: 'General Electric',
    code: 'GE',
    headline: 'GE creates NBCUniversal',
    detail: 'GE combines NBC with Vivendi Universal Entertainment.',
    tone: 'shift',
    source: 'https://www.wired.com/2003/10/vivendi-ge-form-mega-merger',
  },
  {
    year: 2005,
    companyName: 'BP',
    code: 'BP',
    headline: 'BP Texas City disaster',
    detail: 'A refinery explosion kills 15 workers and becomes a defining safety failure.',
    tone: 'caution',
    source: 'https://www.csb.gov/bp-america-texas-city-refinery-explosion/',
  },
  {
    year: 2006,
    companyName: 'ICBC',
    code: '1398.HK',
    headline: 'ICBC pulls off record IPO',
    detail: 'The bank lists in Hong Kong and Shanghai in the world record IPO of its time.',
    tone: 'milestone',
    source: 'https://www.investopedia.com/articles/investing/011215/top-10-largest-global-ipos-all-time.asp',
  },
  {
    year: 2007,
    companyName: 'PetroChina',
    code: '0857.HK',
    headline: 'PetroChina touches $1T',
    detail: 'Its Shanghai debut briefly makes it the first company near a trillion-dollar value.',
    tone: 'milestone',
    source: 'https://www.investopedia.com/significant-financial-events-8700894',
  },
  {
    year: 2008,
    companyName: 'Exxon Mobil',
    code: 'XOM',
    headline: 'Exxon sets profit record',
    detail: 'Annual profit reaches about $45.2B during the oil-price surge.',
    tone: 'milestone',
    source: 'https://www.investopedia.com/exxon-mobil-posts-record-annual-profit-7104073',
  },
  {
    year: 2009,
    companyName: 'Microsoft',
    code: 'MSFT',
    headline: 'Windows 7 goes worldwide',
    detail: 'Microsoft launches Windows 7 globally after Vista struggles.',
    tone: 'shift',
    source: 'https://blogs.windows.com/windowsexperience/2009/10/22/windows-7-arrives-today-with-new-offers-new-pcs-and-more/',
  },
  {
    year: 2010,
    companyName: 'Apple',
    code: 'AAPL',
    headline: 'Apple launches iPad',
    detail: 'Apple opens the modern tablet category at mass scale.',
    tone: 'milestone',
    source: 'https://www.apple.com/newsroom/2010/01/27Apple-Launches-iPad/',
  },
  {
    year: 2011,
    companyName: 'Apple',
    code: 'AAPL',
    headline: 'Steve Jobs dies',
    detail: 'Apple announces the death of its co-founder and creative force.',
    tone: 'caution',
    source: 'https://www.apple.com/newsroom/2011/10/05Statement-by-Apples-Board-of-Directors/',
  },
  {
    year: 2012,
    companyName: 'Apple',
    code: 'AAPL',
    headline: 'Apple hits a valuation record',
    detail: 'Its market cap rises to roughly $624B, a new non-inflation-adjusted record.',
    tone: 'milestone',
    source: 'https://en.wikipedia.org/wiki/Apple_Inc.',
  },
  {
    year: 2013,
    companyName: 'Microsoft',
    code: 'MSFT',
    headline: 'Microsoft moves for Nokia phones',
    detail: 'Microsoft announces a first-party mobile hardware bet.',
    tone: 'caution',
    source: 'https://en.wikipedia.org/wiki/Microsoft_Mobile',
  },
  {
    year: 2014,
    companyName: 'Apple',
    code: 'AAPL',
    headline: 'iPhone 6 and Apple Pay arrive',
    detail: 'Apple moves to larger iPhones and launches its payments push.',
    tone: 'growth',
    source: 'https://www.apple.com/newsroom/2014/09/09Apple-Announces-iPhone-6-iPhone-6-Plus-The-Biggest-Advancements-in-iPhone-History/',
  },
  {
    year: 2015,
    companyName: 'Alphabet (Google)',
    code: 'GOOG',
    headline: 'Google becomes Alphabet',
    detail: 'Google reorganizes under a new holding-company structure.',
    tone: 'shift',
    source: 'https://abc.xyz/',
  },
  {
    year: 2016,
    companyName: 'Microsoft',
    code: 'MSFT',
    headline: 'Microsoft buys LinkedIn',
    detail: 'A $26.2B all-cash deal expands Microsoft into the professional graph.',
    tone: 'growth',
    source: 'https://news.microsoft.com/source/2016/06/13/microsoft-to-acquire-linkedin/',
  },
  {
    year: 2017,
    companyName: 'Apple',
    code: 'AAPL',
    headline: 'Apple unveils iPhone X',
    detail: 'The iPhone shifts to Face ID, OLED, and an all-screen design.',
    tone: 'milestone',
    source: 'https://www.apple.com/newsroom/2017/09/the-future-is-here-iphone-x/',
  },
  {
    year: 2018,
    companyName: 'Apple',
    code: 'AAPL',
    headline: 'Apple reaches $1T',
    detail: 'Apple becomes the first publicly traded U.S. company valued at $1T.',
    tone: 'milestone',
    source: 'https://www.cnbc.com/2018/08/02/apple-hits-1-trillion-in-market-value.html',
  },
  {
    year: 2019,
    companyName: 'Saudi Aramco',
    code: '2222.SR',
    headline: "Aramco's record IPO",
    detail: 'Saudi Aramco raises $25.6B and debuts as the largest listed company.',
    tone: 'milestone',
    source: 'https://www.theguardian.com/business/2019/dec/11/saudi-aramco-becomes-most-valuable-listed-company-in-history',
  },
  {
    year: 2020,
    companyName: 'Apple',
    code: 'AAPL',
    headline: 'Apple reaches $2T',
    detail: 'Apple doubles its trillion-dollar milestone in just two years.',
    tone: 'milestone',
    source: 'https://www.axios.com/2020/08/19/apple-2-trillion-valuation',
  },
  {
    year: 2021,
    companyName: 'Tesla',
    code: 'TSLA',
    headline: 'Tesla joins the $1T club',
    detail: 'A Hertz order helps push Tesla above a trillion-dollar market value.',
    tone: 'growth',
    source: 'https://www.reuters.com/business/autos-transportation/tesla-joins-1-trillion-club-hertz-order-2021-10-25/',
  },
  {
    year: 2022,
    companyName: 'Microsoft',
    code: 'MSFT',
    headline: 'Microsoft bids for Activision',
    detail: 'A $68.7B gaming deal aims to bring Call of Duty and Blizzard under Xbox.',
    tone: 'growth',
    source: 'https://news.microsoft.com/2022/01/18/microsoft-to-acquire-activision-blizzard-to-bring-the-joy-and-community-of-gaming-to-everyone-across-every-device/',
  },
  {
    year: 2023,
    companyName: 'NVIDIA',
    code: 'NVDA',
    headline: 'NVIDIA rides AI to $1T',
    detail: 'AI-chip demand lifts NVIDIA into the trillion-dollar club.',
    tone: 'growth',
    source: 'https://www.cnbc.com/2023/05/30/nvidia-touches-1-trillion-market-cap.html',
  },
  {
    year: 2024,
    companyName: 'NVIDIA',
    code: 'NVDA',
    headline: 'NVIDIA becomes No. 1',
    detail: 'NVIDIA passes Microsoft and Apple as the world AI trade accelerates.',
    tone: 'growth',
    source: 'https://en.wikipedia.org/wiki/Nvidia',
  },
  {
    year: 2025,
    companyName: 'NVIDIA',
    code: 'NVDA',
    headline: 'NVIDIA becomes first $4T company',
    detail: 'NVIDIA crosses the $4T market-cap line as AI infrastructure spending booms.',
    tone: 'milestone',
    source: 'https://www.tomshardware.com/pc-components/gpus/nvidia-is-the-first-company-to-reach-usd4-trillion-market-capitalization-crosses-milestone-briefly-on-july-9',
  },
  {
    year: 2026,
    companyName: 'SpaceX',
    code: 'SPCX',
    headline: 'SpaceX goes public in record IPO',
    detail: 'The IPO raises $75B and pushes SpaceX above a $2T market value.',
    tone: 'milestone',
    source: 'https://www.businessinsider.com/spacex-ipo-10-largest-public-offerings-ranked-by-proceeds-2026-6',
  },
] as const satisfies readonly GlobalMarketCapEvent[];

export const globalMarketCapEventByYear: ReadonlyMap<number, GlobalMarketCapEvent> =
  new Map(globalMarketCapEvents.map((event) => [event.year, event]));
